export const en = {
    'app.title': 'Employee Management',
    'employees': 'Employees',
    'employee.actions': 'Actions',
    'employees.list': 'Employee List',
    'employees.add': 'Add New Employee',
    'employees.edit': 'Edit Employee',
    'employees.delete': 'Delete Employee',
    'employee.firstName': 'First Name',
    'employee.lastName': 'Last Name',
    'employee.dateOfEmployment': 'Date of Employment',
    'employee.dateOfBirth': 'Date of Birth',
    'employee.phone': 'Phone',
    'employee.email': 'Email',
    'employee.department': 'Department',
    'employee.position': 'Position',
    'button.save': 'Save',
    'button.update': 'Update',
    'button.cancel': 'Cancel',
    'button.proceed': 'Proceed',
    'button.delete': 'Delete',
    'button.edit': 'Edit',
    'confirmation.updateEmployee': 'Are you sure you want to update this employee?',
    'confirmation.deleteEmployee': 'Are you sure you want to delete this employee?',
    'confirmation.saveChanges': 'Are you sure you want to save these changes?',
    'error.required': 'This field is required',
    'error.email': 'Please enter a valid email address',
    'error.phone': 'Please enter a valid phone number',
    'positions.junior': 'Junior',
    'positions.medior': 'Medior',
    'positions.senior': 'Senior',
    'departments.analytics': 'Analytics',
    'departments.tech': 'Tech',
    'search': 'Search',
    'list.empty': 'No records found',
    'add_employees': 'Add Employee',
    'cancel': 'Cancel',
    'proceed': 'Proceed',
    'select.department': 'Select Department',
    'select.position': 'Select Position',
    error: {
        required: 'This field is required',
        email: 'Please enter a valid email address',
        phone: 'Please enter a valid phone number',
        date: 'Please enter a valid date in DD/MM/YYYY format'
    },

    // Input field hints
    hint: {
        phone: 'Format: +(90) 532 123 45 67',
        date: 'Format: DD/MM/YYYY'
    },
    '404.title': 'Page Not Found',
    '404.message': 'The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.',
    '404.backToHome': 'Back to Home'
};